import { stat, mkdir } from 'node:fs/promises';
import { join, relative, dirname } from 'node:path';
import { URL, fileURLToPath } from 'node:url';

import { suite, test, assert } from 'vitest';

import { transpile, writeFiles } from '../src/index.js';

import { getDefaultComponentFixtures, LOCAL_TEST_COMPONENTS_JS_DIR } from './common.js';
import { nodeExec, readFixtureFlags, runTSCodegen } from './helpers.js';

/**
 * To run the runtime tests specified below, transpilation must be performed
 *
 * Paths for required dependencies are relative to the `test/output` folder,
 * which is generated by codegen.js tests or code in this file, depending on
 * which tests run first.
 */
const CODEGEN_TRANSPILE_DEPS = {
    dummy_proxy: ['dummy_proxy/dummy_proxy.js'],
    example_guest_export: ['example_guest_export/example_guest_export.js'],
    example_guest_import: ['example_guest_import/example_guest_import.js'],
    flavorful: ['flavorful/flavorful.js'],
    'list-adapter-fusion': ['list-adapter-fusion/list-adapter-fusion.js'],
    lists: ['lists/lists.js'],
    'many-arguments': ['many-arguments/many-arguments.js'],
    'multi-version': ['multi-version/multi-version.js'],
    numbers: ['numbers/numbers.js'],
    records: ['records/records.js'],
    'strings.async+js': ['strings.async+js/strings.async+js.js'],
    'strings.sync+js': ['strings.sync+js/strings.sync+js.js'],
    'strings.sync': ['strings.sync/strings.sync.js'],
    smoke: ['smoke/smoke.js'],
    strings: ['strings/strings.js'],
    variants: ['variants/variants.js', 'helpers.js'],
    resource_borrow_simple: ['resource_borrow_simple/resource_borrow_simple.js'],
    asmjs_bigint: ['asmjs_bigint/asmjs_bigint.js'],
};

// NOTE: if you find this test failing despite code changes, you may need to clear the test/output folder
suite('runtime', async () => {
    // Get path to TS Code
    const tsCodeDir = fileURLToPath(new URL('./fixtures/componentize/runtime', import.meta.url));

    // Pre-process the list of fixtures to get the runtime specific tests
    const existingComponentDir = fileURLToPath(new URL('./fixtures/components/runtime', import.meta.url));
    const rawFixtures = await getDefaultComponentFixtures(existingComponentDir);

    const runtimes = (
        await Promise.all(
            rawFixtures
                .filter((f) => !f.startsWith('dummy_'))
                .filter((f) => !f.startsWith('wasi-http-proxy'))
                // Get the fixture, along with a runtime test name
                .map((f) => [f, f.replace(/(\.component)?\.(wat|wasm)$/, '')])
                .map(([filename, testName]) => {
                    const tsPath = join(tsCodeDir, `${testName}.ts`);
                    return stat(tsPath)
                        .then(() => [filename, testName, tsPath])
                        .catch(() => null);
                }),
        )
    ).filter((v) => v !== null);

    // NOTE: we have to use a tsconfig.json relative path, since baseUrl will be deprecated in TSConfig eventually
    const tsConfigPath = fileURLToPath(new URL('./fixtures/componentize/runtime/tsconfig.json', import.meta.url));
    await mkdir(LOCAL_TEST_COMPONENTS_JS_DIR, { recursive: true });

    // Transpile JS test code
    await runTSCodegen({
        tsConfigPath,
        configOverrides: {
            include: runtimes.map(
                ([_fixtureName, _testName, tsPath]) => './' + relative(dirname(tsConfigPath), tsPath),
            ),
            compilerOptions: {
                outDir: './' + relative(dirname(tsConfigPath), LOCAL_TEST_COMPONENTS_JS_DIR),
            },
        },
    });

    // Create all runtime tests
    const componentFixturesFolderPath = fileURLToPath(new URL('./fixtures/components/runtime', import.meta.url));
    for (const [fixtureName, testName, tsPath] of runtimes) {
        test.concurrent(testName, async () => {
            // Perform transpilation on deps where necessary
            if (CODEGEN_TRANSPILE_DEPS[testName]) {
                for (const filename of CODEGEN_TRANSPILE_DEPS[testName]) {
                    const requiredOutputPath = join(LOCAL_TEST_COMPONENTS_JS_DIR, filename);

                    // Read & parse transpile flags at top of individual fixtures
                    const transpileOpts = await readFixtureFlags(tsPath);

                    // Perform transpilation of the generated folder
                    const componentFixturePath = join(componentFixturesFolderPath, fixtureName);
                    const outputDirPath = join(LOCAL_TEST_COMPONENTS_JS_DIR, testName);
                    const { files } = await transpile(componentFixturePath, {
                        name: testName,
                        ...transpileOpts,
                        outputDir: outputDirPath,
                    });
                    await writeFiles(files, { baseDir: outputDirPath });

                    assert.ok((await stat(requiredOutputPath)).isFile());
                }
            }

            // Run the post-TS compilation test file (now that deps have been resolved)
            const testFilePath = join(LOCAL_TEST_COMPONENTS_JS_DIR, `${testName}.js`);
            const { stderr } = await nodeExec(testFilePath);
            assert.strictEqual(stderr, '');
        });
    }
});
