version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'npm'
    directories:
      - '/*'
      - '/packages/preview2-shim'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'
    groups:
      dev-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch

  - package-ecosystem: 'npm'
    directories:
      - '/examples/components/*'
    groups:
      example-dependencies:
        update-types:
          - major
          - minor
          - patch
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/New_York'

  - package-ecosystem: "cargo"
    directories:
      - '/crates/*'
    schedule:
      interval: "daily"
      
