minimumReleaseAge: 10080
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
  puppeteer: true

packages:
  - packages/jco
  - packages/bare-jco
  - packages/jco-transpile
  - packages/jco-std
  - packages/preview2-shim
  - packages/preview3-shim
  - examples/components/add
  - examples/components/adder
  - examples/components/builtin-bundle-ts
  - examples/components/fs-write-file
  - examples/components/host-logging
  - examples/components/http-hello-world
  - examples/components/http-server-fetch-handler
  - examples/components/http-server-hono
  - examples/components/http-server-hono-with-bindings
  - examples/components/node-compat
  - examples/components/node-fetch
  - examples/components/string-reverse
  - examples/components/string-reverse-upper
  - examples/components/ts-resource-export
  - examples/components/ts-resource-import
  - examples/components/typegen-async-export
  - examples/components/webidl-book-library
  - examples/transpile/p3-stream-chat

catalog:
  '@bytecodealliance/componentize-js': ^0.21.0
  '@rolldown/binding-android-arm64': ^1.2.0
  '@rolldown/binding-darwin-arm64': ^1.2.0
  '@rolldown/binding-darwin-x64': ^1.2.0
  '@rolldown/binding-freebsd-x64': ^1.2.0
  '@rolldown/binding-linux-arm-gnueabihf': ^1.2.0
  '@rolldown/binding-linux-arm64-gnu': ^1.2.0
  '@rolldown/binding-linux-arm64-musl': ^1.2.0
  '@rolldown/binding-linux-ppc64-gnu': ^1.2.0
  '@rolldown/binding-linux-s390x-gnu': ^1.2.0
  '@rolldown/binding-linux-x64-gnu': ^1.2.0
  '@rolldown/binding-linux-x64-musl': ^1.2.0
  '@rolldown/binding-openharmony-arm64': ^1.2.0
  '@rolldown/binding-wasm32-wasi': ^1.2.0
  '@rolldown/binding-win32-arm64-msvc': ^1.2.0
  '@rolldown/binding-win32-x64-msvc': ^1.2.0
  mime: ^4.0.7
  puppeteer: ^25.1.0
  rolldown: ^1.2.0
  typescript: ^6.0.3
  vitest: ^4.0.8
  which: ^2.0.2

minimumReleaseAgeExclude:
  - '@bytecodealliance/componentize-js@0.21.0'
  - '@bytecodealliance/jco-transpile@0.3.7 || 0.3.8 || 0.3.9 || 0.4.0 || 0.4.1 || 0.4.2'
  - '@bytecodealliance/preview2-shim@0.19.0'
  - '@bytecodealliance/preview3-shim@0.1.2 || 0.2.0'
  - '@puppeteer/browsers@3.0.4'
  - '@rolldown/binding-android-arm64@1.2.0'
  - '@rolldown/binding-darwin-arm64@1.2.0'
  - '@rolldown/binding-darwin-x64@1.2.0'
  - '@rolldown/binding-freebsd-x64@1.2.0'
  - '@rolldown/binding-linux-arm-gnueabihf@1.2.0'
  - '@rolldown/binding-linux-arm64-gnu@1.2.0'
  - '@rolldown/binding-linux-arm64-musl@1.2.0'
  - '@rolldown/binding-linux-ppc64-gnu@1.2.0'
  - '@rolldown/binding-linux-s390x-gnu@1.2.0'
  - '@rolldown/binding-linux-x64-gnu@1.2.0'
  - '@rolldown/binding-linux-x64-musl@1.2.0'
  - '@rolldown/binding-openharmony-arm64@1.2.0'
  - '@rolldown/binding-wasm32-wasi@1.2.0'
  - '@rolldown/binding-win32-arm64-msvc@1.2.0'
  - '@rolldown/binding-win32-x64-msvc@1.2.0'
  - hono@4.12.27
  - rolldown@1.2.0
  - puppeteer-core@25.1.0
  - puppeteer@25.1.0
  - ws@8.21.0
