[package]
name = "xtask"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { workspace = true }
js-component-bindgen = { path = "../crates/js-component-bindgen" }
structopt = "0.3.25"
wit-component = { workspace = true }
xshell = "0.1.17"

[build-dependencies]
anyhow = { workspace = true }
js-component-bindgen = { path = "../crates/js-component-bindgen" }
wit-component = { workspace = true }
