just := env_var_or_default("JUST", just_executable())
wac := env_var_or_default("WAC", "wac")

@_default:
    {{just}} --list

# Build all components for test
[group('build')]
build:
    {{just}} build-jco-issue-1380
    {{just}} build-jco-issue-1381
    {{just}} build-jco-issue-1383
    {{just}} build-jco-issue-1384

# Build the components required to test jco issue #1380
[group('build')]
@build-jco-issue-1380:
    echo "==> building jco-issue-1380 caller (cpp)..."
    mkdir -p output/jco-issue-1380
    {{just}} -f cpp/jco-issue-1380/caller/justfile build
    echo "==> building jco-issue-1380 callee (python)..."
    mv cpp/jco-issue-1380/caller/component.wasm output/jco-issue-1380/caller.wasm
    {{just}} -f python/jco-issue-1380/callee/justfile build
    echo "==> composing components..."
    mv python/jco-issue-1380/callee/component.wasm output/jco-issue-1380/callee.wasm
    {{wac}} plug \
       output/jco-issue-1380/caller.wasm \
       --plug output/jco-issue-1380/callee.wasm \
       -o output/jco-issue-1380/composed.wasm

# Build the components required to test jco issue #1381
[group('build')]
@build-jco-issue-1381:
    echo "==> building jco-issue-1381 caller (cpp)..."
    mkdir -p output/jco-issue-1381
    {{just}} -f cpp/jco-issue-1381/caller/justfile build
    echo "==> building jco-issue-1381 callee (python)..."
    mv cpp/jco-issue-1381/caller/component.wasm output/jco-issue-1381/caller.wasm
    {{just}} -f python/jco-issue-1381/callee/justfile build
    echo "==> composing components..."
    mv python/jco-issue-1381/callee/component.wasm output/jco-issue-1381/callee.wasm
    {{wac}} plug \
       output/jco-issue-1381/caller.wasm \
       --plug output/jco-issue-1381/callee.wasm \
       -o output/jco-issue-1381/composed.wasm

# Build the components required to test jco issue #1383
[group('build')]
@build-jco-issue-1383:
    echo "==> building jco-issue-1383 caller (cpp)..."
    mkdir -p output/jco-issue-1383
    {{just}} -f cpp/jco-issue-1383/caller/justfile build
    echo "==> building jco-issue-1383 callee (python)..."
    mv cpp/jco-issue-1383/caller/component.wasm output/jco-issue-1383/caller.wasm
    {{just}} -f python/jco-issue-1383/callee/justfile build
    echo "==> composing components..."
    mv python/jco-issue-1383/callee/component.wasm output/jco-issue-1383/callee.wasm
    {{wac}} plug \
       output/jco-issue-1383/caller.wasm \
       --plug output/jco-issue-1383/callee.wasm \
       -o output/jco-issue-1383/composed.wasm

# Build the components required to test jco issue #1384
[group('build')]
@build-jco-issue-1384:
    echo "==> building jco-issue-1384 caller (cpp)..."
    mkdir -p output/jco-issue-1384
    {{just}} -f cpp/jco-issue-1384/caller/justfile build
    echo "==> building jco-issue-1384 callee (python)..."
    mv cpp/jco-issue-1384/caller/component.wasm output/jco-issue-1384/caller.wasm
    {{just}} -f python/jco-issue-1384/callee/justfile build
    echo "==> composing components..."
    mv python/jco-issue-1384/callee/component.wasm output/jco-issue-1384/callee.wasm
    {{wac}} plug \
       output/jco-issue-1384/caller.wasm \
       --plug output/jco-issue-1384/callee.wasm \
       -o output/jco-issue-1384/composed.wasm
