[package]
name = "wit-bindgen-gen-host-js"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version.workspace = true
edition.workspace = true

[lib]
doctest = false
test = false

[dependencies]
wit-bindgen-core = { workspace = true }
heck = { workspace = true }
structopt = { workspace = true, optional = true }

[dev-dependencies]
test-helpers = { path = '../test-helpers', features = ['host-js'] }
