package jco:test-components;

interface local-run-async {
    run: async func();
}

interface local-run-string {
    run: func() -> string;
}

interface get-string {
    get-string: func() -> string;
}

interface async-add-s32 {
    add: async func(a: s32, b: s32) -> result<s32, string>;
}

interface resources {
    resource example-resource {
        constructor(id: u32);
        get-id: func() -> u32;
    }
}

interface example-types {
    variant example-variant {
        num(u32),
        str(string),
        float(f32),
        maybe-u32(option<u32>),
    }

    enum example-enum {
        first,
        second,
        third,
    }

    record example-record {
        id: u32,
        id-str: string,
    }

    flags example-flags {
        first,
        second,
        third,
    }
}

interface get-stream-async {
    use resources.{example-resource};
    use example-types.{example-variant, example-enum, example-record, example-flags};

    resource example-guest-resource {
        constructor(id: u32);
        get-id: func() -> u32;
        get-id-async: async func() -> u32;
    }

    get-stream-u32: async func(vals: list<u32>) -> result<stream<u32>, string>;
    get-stream-s32: async func(vals: list<s32>) -> result<stream<s32>, string>;

    get-stream-u8: async func(vals: list<u8>) -> result<stream<u8>, string>;
    get-stream-s8: async func(vals: list<s8>) -> result<stream<s8>, string>;

    get-stream-u16: async func(vals: list<u16>) -> result<stream<u16>, string>;
    get-stream-s16: async func(vals: list<s16>) -> result<stream<s16>, string>;

    get-stream-u64: async func(vals: list<u64>) -> result<stream<u64>, string>;
    get-stream-s64: async func(vals: list<s64>) -> result<stream<s64>, string>;

    get-stream-f32: async func(vals: list<f32>) -> result<stream<f32>, string>;

    get-stream-f64: async func(vals: list<f64>) -> result<stream<f64>, string>;

    get-stream-bool: async func(vals: list<bool>) -> result<stream<bool>, string>;

    // NOTE: stream<char> is not yet supported upstream (stream<u8> can be used instead)
    //
    // get-stream-char: async func(vals: list<char>) -> result<stream<char>, string>;

    get-stream-string: async func(vals: list<string>) -> result<stream<string>, string>;

    get-stream-record: async func(vals: list<example-record>) -> result<stream<example-record>, string>;

    get-stream-variant: async func(vals: list<example-variant>) -> result<stream<example-variant>, string>;

    get-stream-list-u8: async func(vals: list<list<u8>>) -> result<stream<list<u8>>, string>;
    get-stream-list-string: async func(vals: list<list<string>>) -> result<stream<list<string>>, string>;
    get-stream-list-record: async func(vals: list<list<example-record>>) -> result<stream<list<example-record>>, string>;
    get-stream-fixed-list-u32: async func(vals: list<list<u32, 5>>) -> result<stream<list<u32, 5>>, string>;

    get-stream-tuple: async func(vals: list<tuple<u32, s32, string>>) -> result<stream<tuple<u32, s32, string>>, string>;

    get-stream-flags: async func(vals: list<example-flags>) -> result<stream<example-flags>, string>;

    get-stream-enum: async func(vals: list<example-enum>) -> result<stream<example-enum>, string>;

    get-stream-option-string: async func(vals: list<option<string>>) -> result<stream<option<string>>, string>;

    get-stream-result-string: async func(vals: list<result<string, string>>) -> result<stream<result<string, string>>, string>;

    // NOTE: stream<borrow<t>> is not supoprted
    //
    // get-stream-example-resource-borrow: async func(
    //   vals: list<borrow<example-resource>>
    // ) -> result<stream<borrow<example-resource>>, string>;

    get-stream-example-resource-own: async func(vals: list<u32>) -> result<stream<example-guest-resource>, string>;
    get-example-resource-own-disposes: func() -> u32;

    get-stream-example-resource-own-attr: async func(vals: list<example-resource>) -> result<stream<u32>, string>;

    get-stream-stream-string: async func(vals: list<string>) -> result<stream<stream<string>>, string>;

    //get-stream-future-string: async func(vals: list<future<string>>) -> result<stream<future<string>>, string>;
}

world async-simple-import {
  import load-u32: async func() -> u32;
  import load-string: async func() -> string;

  export get-u32: async func() -> u32;
  export get-string: async func() -> string;
}

world async-error-context {
  export local-run-async;
}

world async-flat-param-adder {
  export async-add-s32;
}

world async-simple-return {
  export get-u32: async func() -> u32;
  export get-string: async func() -> string;
}

world stream-tx {
  import resources;
  export get-stream-async;
}

interface sleep-post-return {
  run: async func(sleep-time-millis: u64);
}

interface sleep {
  sleep-millis: async func(time-in-millis: u64);
}

world sleep-post-return-caller {
  import sleep;
  import sleep-post-return;
  export sleep-post-return;
}

world sleep-post-return-callee {
  import sleep;
  export sleep-post-return;
}

interface fixed-length-lists-fn {
  takes-returns-fixed: func(bools: list<bool, 17>) -> result<list<u8, 32>, string>;
}

world fixed-length-lists {
  export fixed-length-lists-fn;
}

world basic-run-string {
    import get-string;
    export get-string;
    export local-run-string;
}

//////////////////
// Stream Usage //
//////////////////

interface use-stream-sync {
          // TODO(fix): optimize host-only stream usage -- detect when the read & write are held by the host
    stream-passthrough: func(s: stream<u32>) -> stream<u32>;
}

interface use-stream-async {
    // use resources.{example-resource};
    use example-types.{example-variant, example-enum, example-record, example-flags};

    stream-passthrough: async func(s: stream<u32>) -> stream<u32>;

    read-stream-values-bool: async func(s: stream<bool>) -> list<bool>;

    read-stream-values-u8: async func(s: stream<u8>) -> list<u8>;
    read-stream-values-s8: async func(s: stream<s8>) -> list<s8>;

    read-stream-values-u16: async func(s: stream<u16>) -> list<u16>;
    read-stream-values-s16: async func(s: stream<s16>) -> list<s16>;

    read-stream-values-u32: async func(s: stream<u32>) -> list<u32>;
    read-stream-values-s32: async func(s: stream<s32>) -> list<s32>;

    read-stream-values-u64: async func(s: stream<u64>) -> list<u64>;
    read-stream-values-s64: async func(s: stream<s64>) -> list<s64>;

    read-stream-values-f32: async func(s: stream<f32>) -> list<f32>;

    read-stream-values-f64: async func(s: stream<f64>) -> list<f64>;

    read-stream-values-string: async func(s: stream<string>) -> list<string>;

    read-stream-values-record: async func(s: stream<example-record>) -> list<example-record>;

    read-stream-values-variant: async func(s: stream<example-variant>) -> list<example-variant>;

    read-stream-values-tuple: async func(s: stream<tuple<u32, s32, string>>) -> list<tuple<u32, s32, string>>;

    read-stream-values-flags: async func(s: stream<example-flags>) -> list<example-flags>;

    read-stream-values-enum: async func(s: stream<example-enum>) -> list<example-enum>;

    read-stream-values-option-string: async func(s: stream<option<string>>) -> list<option<string>>;

    read-stream-values-result-string: async func(s: stream<result<string, string>>) -> list<result<string, string>>;

    read-stream-values-list-u8: async func(s: stream<list<u8>>) -> list<list<u8>>;
    read-stream-values-list-string: async func(s: stream<list<string>>) -> list<list<string>>;
    read-stream-values-fixed-list-u32: async func(s: stream<list<list<u32, 5>>>) -> list<list<list<u32, 5>>>;
    read-stream-values-list-record: async func(s: stream<list<example-record>>) -> list<list<example-record>>;

    // // NOTE: the check here will be whether the resources are disposed inside the component properly
    // read-stream-values-example-resource-own: async func(s: stream<example-resource>);

    // read-stream-values-example-resource-own-attr: async func(s: stream<example-resource>) -> list<u32>;

    // read-stream-values-stream-string: async func(s: stream<stream<string>>) -> list<list<string>>;

    //read-stream-values-future-string: async func(vals: list<future<string>>) -> result<stream<future<string>>, string>;
}

world stream-rx {
    // import resources;

    export use-stream-sync;
    export use-stream-async;
}