package example:http-server-fetch-handler;

world component {
    /// NOTE: StarlingMonkey picks up on this export along with the 
    /// *lack* of an explicit `incomingHandler` ES module export to add the fetch
    /// event handler that is usable from a service worker.
    export wasi:http/incoming-handler@0.2.3;
}