/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Invoke the host's `posix_fadvise` implementation.
 *
 * This is an internal binding. The JavaScript wrapper validates arguments and
 * turns the returned errno into a Node-style exception.
 */
export declare function fadviseRaw(fd: number, offset: string, length: string, advice: string): number
