package rpc:caller;

interface api {
  test1: func() -> list<tuple<string, u64>>;
  test2: func() -> u64;
  test3: func() -> u64;
}

world caller {
  import rpc:counters-stub/stub-counters;
  export api;
  export tuples: func() -> list<tuple<string, u64>>;
}