/**
 * This file implements helpers and relevant types for use with `wasi:http@0.2.6`
 *
 * @see: https://github.com/WebAssembly/wasi-http
 */

import { type IncomingRequest, IncomingBody } from "wasi:http/types@0.2.6";

import { genReadWASIRequestFn } from "../../../0.2.x/http/types/request.js";

/**
 * Create a web-platform `Request` from a `wasi:http/incoming-handler` `incoming-request`.
 *
 * This method expects the `wasiIncomingRequest` object to be compliant with WASI 0.2.x,
 * with an implemention as generated by the jco/componentize-js JS ecosystem.
 *
 * @param {any} wasiIncomingRequest - request handler for a WASI HTTP request
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/Request
 * @see https://github.com/WebAssembly/wasi-http
 */
export async function readWASIRequest(wasiIncomingRequest: IncomingRequest): Promise<Request> {
  const f = genReadWASIRequestFn(IncomingBody);
  return await f(wasiIncomingRequest);
}
