[book]
title = "jco"
authors = ["Guy Bedford", "Yosh Wuyts", "Victor Adossi"]
language = "en"
multilingual = false

src = "src"

[output.html]
git-repository-url = "https://github.com/bytecodealliance/jco"

[preprocessor.alerts]

[output.linkcheck]
