package example:http-server-hono-with-bindings;

world component {
    // NOTE: Unlike the simple http-server-hono example,
    // since we use middlewares that depend on 'wasi:cli/environment'
    // and 'wasi:config/store', we must declare those WASI interfaces
    // as imports for this component.
    import wasi:cli/environment@0.2.6;
    import wasi:config/store@0.2.0-rc.1;

    export wasi:http/incoming-handler@0.2.6;
}