name: lint-pr

on:
  workflow_run:
    workflows:
      - receive-pr
    types:
      - completed

permissions:
  contents: none

jobs:
  cc-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            debug
            docs
            feat
            fix
            perf
            refactor
            release
            revert
            style
            test
          scopes: |
            bindgen
            ci
            deps
            docs
            examples
            jco
            ops
            p2-shim
            p3-shim
            transpile
